spring:
  application:
    name: axiom
  datasource:
    url: jdbc:postgresql://localhost:5433/axiomdb
    driverClassName: org.postgresql.Driver
    username: axiomuser
    password: axiompassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: c3VwZXJTZWNyZXRLZXlGb3JKV1QxMjM0NTY3ODkwMTIzNDU2Nzg5MA==
  expiration: 86400000