spring:
  application:
    name: axiom
  datasource:
    url: jdbc:postgresql://localhost:5433/axiomdb
    driverClassName: org.postgresql.Driver
    username: axiomuser
    password: axiompassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: c3VwZXJTZWNyZXRLZXlGb3JKV1QxMjM0NTY3ODkwMTIzNDU2Nzg5MA==
  expiration: 86400000

storage:
  s3:
    endpoint: http://localhost:9000
    region: eu-central-1
    bucket: axiom-attachments
    access-key: axiomminio
    secret-key: axiomminiopassword
